# Generated by Django 5.2.8 on 2025-11-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("color", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Box_Info",
            },
        ),
        migrations.CreateModel(
            name="Warehouse_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
            ],
            options={
                "db_table": "Warehouse_Info",
            },
        ),
        migrations.DeleteModel(
            name="Box",
        ),
        migrations.AddField(
            model_name="box_info",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.warehouse_info"
            ),
        ),
    ]
