# Generated by Django 5.2.8 on 2025-12-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_box_info_warehouse_info_delete_box_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse_info",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse_info",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="warehouse_info",
            name="length",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="warehouse_info",
            name="width",
            field=models.FloatField(default=0),
        ),
    ]
