# Generated by Django 5.2.8 on 2025-12-29 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_warehouse_info_user_alter_warehouse_info_height_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="box_info",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="members.warehouse_info",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse_info",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
